# Generated by Django 3.1.3 on 2020-11-14 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pichub', '0003_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='pichub.category'),
        ),
    ]
